apiVersion: v2
name: CHART_NAME
description: "%%DESCRIPTION%%"
version: 0.1.0
appVersion: "%%UPSTREAM_PROJECT_VERSION%%"
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
annotations:
  category: "%%CHOOSE_ONE_FROM_CHART_CATEGORIES_FILE%%"
  licenses: Apache-2.0
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/%%IMAGE_NAME%%/img/%%IMAGE_NAME%%-stack-220x234.png
keywords:
  - "%%UPSTREAM_PROJECT_KEYWORD%%"
  - "%%UPSTREAM_PROJECT_KEYWORD%%"
  - ...
maintainers:
  - name: Broadcom, Inc. All Rights Reserved.
    url: https://github.com/bitnami/charts
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/%%IMAGE_NAME%%
  - https://github.com/bitnami/containers/tree/main/bitnami/%%IMAGE_NAME%%
  - "%%UPSTREAM_PROJECT_SOURCE_CODE_URL%%"
  - ...
